const SUPABASE_URL = "PASTE-YOUR-SUPABASE-PROJECT-URL-HERE";
const SUPABASE_PUBLISHABLE_KEY = "PASTE-YOUR-PUBLISHABLE-KEY-HERE";

const supabaseClient = window.supabase.createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
